### ISSUE TITLE
is there any blog or tutorial for this ?

### ISSUE THREAD

**Issue by mlotfi2005** [usemodj/angularjs-express-mysql#1]
Hi,
I was browsing looking to learn angular, I found your github, the Readme does not explain what is this for , the schema has only one table "users" , where the other data is stored in ? for example in the demo you can create a ticket.
Thanks,

**Comment by usemodj** [comment]
the schema is auto generated if the server(backend) is running.
backend/models/ tables list

**Comment by mlotfi2005** [comment]
Thanks for your reply, 
I tried run it in my local machine but this is what I got :
http://s9.postimg.org/k6qq5dnin/nodesoft2.png

**Comment by usemodj** [comment]
Check again following process:

Ubuntu:

$ sudo apt-get install nodejs npm imagemagick

$ sudo ln -s /usr/bin/nodejs /usr/bin/node
$ cd backend
$ backend> sudo npm install

$ cd ../frontend
$ frontend> sudo npm install
$ frontend> bower install
$ frontend> mkdir app/uploads

## Create database:

CREATE DATABASE nodesoft2 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
-- Setting Database Info:

$ backend> vim config/settings.js
   ...
    database: {
        database: "nodesoft2",
        user: "root",
        password: "",
    }
   ...

## Run Server

cd ../backend
backend> npm start 

Browser connect: 
  http://localhost:3000

On Chrome or FireFox Browser
Click keyboard F12 key, and  Console tab show  error message or infomation.
check this message.

**Comment by usemodj** [comment]
check "bower_components/bootstrap/dist/css/bootstrap.css" file included in index.html

Maybe "grunt build" process does not include "bootstrap.css" file automatically.

frontend/app/index.html

```
<head>
...
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <!-- build:css styles/vendor.css -->
    <!-- bower:css -->
    <link rel="stylesheet" href="bower_components/select2/select2.css" />
    <link rel="stylesheet" href="bower_components/angular-ui-tree/dist/angular-ui-tree.min.css" />
    <link rel="stylesheet" href="bower_components/bootstrap-markdown/css/bootstrap-markdown.min.css" />
    <link rel="stylesheet" href="bower_components/fontawesome/css/font-awesome.css" />
    <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.css" />
    <!-- endbower -->
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="bower_components/angular-treeview/css/angular.treeview.css"/>
    <link rel="stylesheet" href="bower_components/jquery-ui/themes/base/all.css" />
    <!-- endbuild -->

    <!-- build:css({.tmp,app}) styles/main.css -->
    <link rel="stylesheet" href="styles/main.css">
    <!-- endbuild -->

...
</head>
```

**Comment by mlotfi2005** [comment]
Thanks, it's working now, it was missing 
<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />

what table has users ?
I tried to singup  but I got 

POST http://localhost:3000/users 500 (Internal Server Error)(anonymous function) @ angular.js:10506sendReq @ angular.js:10325$get.serverRequest @ angular.js:10037processQueue @ angular.js:14551(anonymous function) @ angular.js:14567$get.Scope.$eval @ angular.js:15830$get.Scope.$digest @ angular.js:15641$get.Scope.$apply @ angular.js:15935(anonymous function) @ angular.js:23244jQuery.event.dispatch @ jquery.js:4435jQuery.event.add.elemData.handle @ jquery.js:4121
angular.js:12314 TypeError: Cannot read property '$setValidity' of undefined
    at signup.js:26
    at Object.forEach (angular.js:336)
    at signup.js:19
    at authfactory.js:94
    at angular-resource.js:619
    at processQueue (angular.js:14551)
    at angular.js:14567
    at Scope.$get.Scope.$eval (angular.js:15830)
    at Scope.$get.Scope.$digest (angular.js:15641)
    at Scope.$get.Scope.$apply (angular.js:15935)

and when I tried to login as admin (admin@example.com, admin) I got

POST http://localhost:3000/auth/session 401 (Unauthorized)

Thanks, your help is appreciated.

**Comment by usemodj** [comment]
## Checkout again.

$ git clone https://github.com/usemodj/angularjs-express-mysql.git

## Install packages

$ cd angularjs-express-mysql/backend
$backend> sudo npm install

$backend> cd ../frontend
$frontend> sudo npm install
$frontend> bower install
 ...select angular 1.4.1

## Grunt build

$frontend> grunt build

## Database recreate:

DROP DATABASE nodesoft2;
CREATE DATABASE nodesoft2 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

## Run server

$backend> npm start

## Web login

admin@example.com / admin
